// <auto-generated />
using System;
using GAIA.Infra.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GAIA.Infra.EFCore.Migrations
{
    [DbContext(typeof(GaiaDbContext))]
    partial class GaiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ef-core")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GAIA.Domain.FileStorage.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StoredFiles", "ef-core");
                });

            modelBuilder.Entity("GAIA.Domain.Framework.Framework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Frameworks", "ef-core");
                });

            modelBuilder.Entity("GAIA.Domain.Framework.FrameworkDepth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("Depth", "Name");

                    b.ToTable("FrameworkDepth", "ef-core");
                });

            modelBuilder.Entity("GAIA.Domain.Framework.Scoring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId");

                    b.ToTable("Scoring", "ef-core");
                });

            modelBuilder.Entity("GAIA.Domain.Framework.Framework", b =>
                {
                    b.OwnsOne("GAIA.Domain.Framework.FrameworkNode", "Root", b1 =>
                        {
                            b1.Property<Guid>("FrameworkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("FrameworkId");

                            b1.ToTable("FrameworkRoots", "ef-core");

                            b1.WithOwner()
                                .HasForeignKey("FrameworkId");

                            b1.OwnsMany("GAIA.Domain.Framework.FrameworkNode.Children#FrameworkNode", "Children", b2 =>
                                {
                                    b2.Property<Guid>("RootId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Content")
                                        .HasMaxLength(5000)
                                        .HasColumnType("character varying(5000)");

                                    b2.HasKey("RootId", "Id");

                                    b2.ToTable("FrameworkRootChildren", "ef-core");

                                    b2.WithOwner()
                                        .HasForeignKey("RootId");
                                });

                            b1.Navigation("Children");
                        });

                    b.Navigation("Root")
                        .IsRequired();
                });

            modelBuilder.Entity("GAIA.Domain.Framework.FrameworkDepth", b =>
                {
                    b.HasOne("GAIA.Domain.Framework.Framework", null)
                        .WithMany("Depths")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GAIA.Domain.Framework.Scoring", b =>
                {
                    b.HasOne("GAIA.Domain.Framework.Framework", null)
                        .WithMany("Scorings")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GAIA.Domain.Framework.Framework", b =>
                {
                    b.Navigation("Depths");

                    b.Navigation("Scorings");
                });
#pragma warning restore 612, 618
        }
    }
}
