// <auto-generated />
using System;
using GAIA.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GAIA.Infra.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20251113000000_AddDocuments")]
partial class AddDocuments
{
  /// <inheritdoc />
  protected override void BuildTargetModel(ModelBuilder modelBuilder)
  {
#pragma warning disable 612, 618
    modelBuilder
      .HasAnnotation("ProductVersion", "9.0.9")
      .HasAnnotation("Relational:MaxIdentifierLength", 63);

    Npgsql.EntityFrameworkCore.PostgreSQL.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

    modelBuilder.Entity("GAIA.Domain.Documents.Entities.Document", b =>
    {
      b.Property<Guid>("Id")
        .ValueGeneratedOnAdd()
        .HasColumnType("uuid");

      b.Property<string>("Category")
        .IsRequired()
        .HasMaxLength(100)
        .HasColumnType("character varying(100)");

      b.Property<byte[]>("Content")
        .IsRequired()
        .HasColumnType("bytea");

      b.Property<string>("Name")
        .IsRequired()
        .HasMaxLength(255)
        .HasColumnType("character varying(255)");

      b.Property<string>("Status")
        .IsRequired()
        .HasMaxLength(100)
        .HasColumnType("character varying(100)");

      b.HasKey("Id");

      b.ToTable("Documents", (string)null);
    });
#pragma warning restore 612, 618
  }
}
